@startuml

skinparam defaultTextAlignment center

<style>
rectangle {
  MinimumWidth 250
  MinimumHeight 90
}
</style>

rectangle "**CH Core**\nSwiss Core Profiles, EPR Concepts" as chcore #white;line:darkred;line.bold 
rectangle "**CH Term**\nSwiss Terminology" as chterm #white;line:darkred;line.bold 
rectangle "**CH LAB-Report**\neHealth Suisse / HL7 Switzerland" as chlabreport #white;line:navy;line.bold 
rectangle "**HL7 Europe Laboratory Report**\nHL7 Europe" as eulabreport #white;line:orange;line.bold 
rectangle "**CH ELM**\nFOPH" as chelm #white;line:navy;line.bold 
rectangle "<color:darkred>Core Profiles</color>" as descr1 #line:transparent;back:transparent
rectangle "<color:navy>          Exchange Formats</color>" as descr2 #line:transparent;back:transparent

chcore -right-> chterm #grey : <color:grey>             derived             </color>
chlabreport -up-> chcore #grey : <color:grey> derived</color>
chlabreport -right-> eulabreport #grey : <color:grey>imposeProfile Extension</color>
chelm -up-> chlabreport #grey : <color:grey> derived</color>
descr1 -[hidden]right-> chcore
descr2 -[hidden]right-> chlabreport

@enduml
