# Example/Documentation for the IG YML file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

# Package name
# https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Packagename
id: ch.fhir.ig.ch-elm
canonical: http://fhir.ch/ig/ch-elm
name: CH_ELM
title: "CH ELM (R4)"
description: FHIR® Implementation Guide for the Electronic Laboratory Report of the Swiss Federal Office of Public Health
status: active # draft | active | retired | unknown
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CHE
date: 2024-11-28
version: 1.7.0
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: release # release # ci-build # ci-build 
publisher:
  name: Federal Office of Public Health FOPH
contact:
  - name: Federal Office of Public Health FOPH
    telecom:
      - system: url
        value: https://www.bag.admin.ch/bag/en/home/das-bag/kontakt-standort.html

dependencies:
  hl7.terminology: 5.4.0
  hl7.fhir.eu.laboratory: 0.1.0
  hl7.fhir.uv.ips: 1.1.0
  ch.fhir.ig.ch-lab-report: 1.0.0-ballot
  ch.fhir.ig.ch-core: 5.0.0-ballot
  hl7.fhir.uv.extensions.r4: 1.0.0
  hl7.fhir.extensions.r5: 4.0.1
pages:
  index.md:
    title: Home
  document.md:
    title: FHIR Document (Bundle)   
  logical.md:
    title: Logical Model  
  usecase.md:
    title: Use Case 
  guidance.md:
    title: Guidance
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  api.md:
    title: API
  terminology.md:
    title: Terminology
  changelog.md:
    title: Changelog
  businessrules.md:
    title: Business Rules      

menu:
  Table of Contents: toc.html
  Home: index.html
  Laboratory Report: 
    FHIR Document: document.html
    Logical Model: logical.html
  Use Case: usecase.html
  Guidance: guidance.html
  Profiles: profiles.html
  Extensions: extensions.html
  API: api.html
  Terminology: terminology.html
  Changelog: changelog.html
  Business Rules: businessrules.html
  Artifacts: artifacts.html

# Parameters
# Core FHIR: http://build.fhir.org/codesystem-guide-parameter-code.html
# FHIR Tools IG: http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
parameters:
  allow-extensible-warnings: true
  display-warnings: true
  path-resource:
    - input/resources
    - fsh-generated/resources
  no-narrative: 
    - Bundle/*
    - Composition/*
    - DiagnosticReport/*
    - DocumentReference/*
    - Observation/*
    - Organization/*
    - Patient/*
    - Practitioner/*
    - PractitionerRole/*
    - ServiceRequest/*
    - Specimen/*

  excludettl: true
#  apply-version: false
#  default-version: true

instanceOptions:
  # Determines for which types of Instances SUSHI will automatically set meta.profile
  # if InstanceOf references a profile. Options are:
  # - always: Set meta.profile for all Instances of profiles (default)
  # - never: Do not set meta.profile on any Instances
  # - inline-only: Set meta.profile for only Instances of profiles with Usage set to #inline
  # - standalone-only: Set meta.profile for only Instances of profiles where Usage is any value other than #inline
  setMetaProfile: never

resources:
  Bundle/8Doc-HepatiteB:
    name: 8Doc - HepatiteB
    description: Document for Hepatite B
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/9Doc-HepatiteC:
    name: 9Doc - HepatiteC
    description: Example Document for Hepatite C
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/10Doc-Legionella:
    name: 10Doc - Legionella
    description: Example Document for Legionella
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/11Doc-Malaria:
    name: 11Doc - Malaria
    description: Example Document for Malaria
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/12Doc-Monkeypox:
    name: 12Doc - Monkeypox
    description: Example Document for Monkeypox
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/13Doc-Shigella:
    name: 13Doc - Shigella
    description: Example Document for Shigella
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/14Doc-Neisseriameningitidis-confirmationtest:
    name: 14Doc - Neisseria meningitidis - confirmation test
    description: Example Document for a confirmation test of Neisseria meningitidis by secondary lab (reference laboratory)
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/15Doc-Measles-Seroconversion:
    name: 15Doc - Measles Seroconversion
    description: Example Document Measles Seroconversion
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/16Doc-Dengue-Titer:
    name: 16Doc - Dengue Titer
    description: Example Document Dengue with high IgG Ab-Titer
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/17Doc-Neisseria:
    name: 17Doc - Neisseria meningitidis – microscopic finding
    description: Example Document for a microscopic observation of Neisseria meningitidis by primary lab
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/18Doc-C-diphtheriae:
    name: 18Doc - Corynebacterium diphtheriae 
    description: Example Document for Corynebacterium diphtheriae with specimen specification
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/19Doc-S-pneumoniae:
    name: 19Doc - Streptococcus pneumoniae 
    description: Example Document for Streptococcus pneumoniae
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/20Doc-Vibrio-cholerae:
    name: 20Doc - Vibrio cholerae
    description: Example Document for Vibrio cholerae
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/21Doc-HepatiteE:
    name: 21Doc - Hepatite E
    description: Example Document for Hepatite E
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/22Doc-H-influenzae:
    name: 22Doc - Haemophilus influenzae
    description: Example Document for Haemophilus influenzae
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/23Doc-F-tularensis:
    name: 23Doc - Francisella tularensis with organism specification
    description: Example Document for Francisella tularensis with organism specification
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/24Doc-Chikungunya:
    name: 24Doc - Chikungunya fever 
    description: Example Document for Chikungunya fever
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/25Doc-Tick-borne-encephalitis:
    name: 25Doc - Tick-borne encephalitis
    description: Example Document for Tick-borne encephalitis
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/26Doc-HepatiteA:
    name: 26Doc - Hepatite A
    description: Example Document for Hepatite A
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  # Bundle/27Doc-Coxiella-burnetii:
  #   name: 27Doc - Coxiella burnetii
  #   description: Example Document for Coxiella burnetii
  #   exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/28Doc-Listeria-monocytogenes:
    name: 28Doc - Listeria monocytogenes
    description: Example Document for Listeria monocytogenes
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/29Doc-Rubella:
    name: 29Doc - Rubella
    description: Example Document for Rubella
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/30Doc-Salmonella-enteritidis:
    name: 30Doc - Salmonella enteritidis
    description: Example Document for Salmonella enteritidis
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/32Doc-Rubella-avidity:
    name: 32Doc - Rubella avidity
    description: Example Document for reporting a rubella avidity
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/33Doc-Salmonella-valueString:
    name: 33Doc - Salmonella valueString
    description: Example Document for Salmonella reporting a (new) serotype for which no coding exists
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/34Doc-Brucella:
    name: 34Doc - Brucella
    description: Example Document for Brucella
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/35Doc-CJD:
    name: 35Doc CJD
    description: Example Document for Creutzfeldt-Jakob disease
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/36Doc-Salmonella-paratyphi:
    name: 36Doc - Salmonella paratyphi
    description: Example Document for Salmonella paratyphi
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/37Doc-Zika:
    name: 37Doc - Zika
    description: Example Document for Zika
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/38Doc-Anthrax:
    name: 38Doc - Anthrax
    description: Example Document for Bacillus anthracis
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/39Doc-Botulims:
    name: 39Doc - Botulism
    description: Example Document for Clostridium botulinum
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/40Doc-Crimean-Congo:
    name: 40Doc - Crimean-Congo
    description: Example Document for Crimean-congo virus
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/41Doc-Ebola:
    name: 41Doc - Ebola
    description: Example Document for Ebola virus
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/42Doc-Lassa:
    name: 42Doc - Lassa
    description: Example Document for Lassa virus
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/43Doc-Marburg:
    name: 43Doc - Marburg
    description: Example Document for Marburg virus
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/44Doc-Mers-CoV:
    name: 44Doc - MERS-CoV
    description: Example Document for MERS coronavirus
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/45Doc-Sars-CoV:
    name: 45Doc - SARS-CoV
    description: Example Document for Sars coronavirus
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/46Doc-Yersinia-pestis:
    name: 46Doc - Yersinia pestis
    description: Example Document for Yersinia pestis
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/47Doc-Variola:
    name: 47Doc - Variola
    description: Example Document for Variola
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/48Doc-Mpox-Clade:
    name: 48Doc - Monkeypox Clade
    description: Example Document for Monkeypox Clade
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/49Doc-HIV:
    name: 49Doc - HIV
    description: Example Document for HIV
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/50Doc-HIV-viremia:
    name: 50Doc - HIV-viremia
    description: Example Document for reporting a physical quantity value
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/51Doc-Gelbfieber:
    name: 51Doc - Gelbfieber
    description: Example Document for Yellow fever-virus
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/52Doc-Hantavirus:
    name: 52Doc - Hantavirus
    description: Example Document for Hanta-virus
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/53Doc-InfluenzaHxNy:
    name: 53Doc - Influenza HxNy
    description: Example Document for Influenza A virus reporting a specific subtype
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/54Doc-Poliomyelitis:
    name: 54Doc - Poliomyelitis
    description: Example Document for Polio
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/55Doc-Tollwut:
    name: 55Doc - Tollwut
    description: Example Document for Rabies-virus
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/56Doc-Trichinella-spiralis:
    name: 56Doc - Trichinella spiralis
    description: Example Document for Trichinella
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/57Doc-West-Nile:
    name: 57Doc - West Nile
    description: Example Document for West-Nile-Fever-virus using an organism-specification code
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Binary/Test92-Bundle-WarningBerUidGln:
    extension:
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-format
        valueCode: application/fhir+json
    name: Test92 - Bundle provoking warning for Ber Uid and Gln
    description: Test bundle to verify if incorrect BerUid Gln are detected with warnings
    exampleCanonical: http://hl7.org/fhir/StructureDefinition/Binary
  TestScript/Test92-WarningBerUidGln:
    name: Test92 - Warning for Ber Uid and Gln
    description: Test script to verify if incorrect BerUid Gln are detected with warnings
  Binary/Test93-DocumentReference-Error-FullName-Influenca:
    extension:
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-format
        valueCode: application/fhir+xml
    name: Test93 - DocumentReference with contained Bundle provoking error for full name for Influenca (must be initials)
    description: Test DocumentReference with contained Bundle provoking error for full name for Influenca (must be initials)
    exampleCanonical: http://hl7.org/fhir/StructureDefinition/Binary
  TestScript/Test93-Error-FullName-Influenca:
    name: Test93 - Error if full name is provided by Influenca (should be initials)
    description: Test script to verify error if full name is provided by Influenca (must be initials)
  TestScript/Test94-Ignore-Source-Warning:
    name: Test94 - If warning is ignored for Binding for path (.+) has no source
    description: Test script to verify if warning is ignored for Binding for path (.+) has no source