# Example/Documentation for the IG YML file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

# Package name
# https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Packagename
id: ch.fhir.ig.ch-elm
canonical: http://fhir.ch/ig/ch-elm
name: CH_ELM
title: "CH ELM (R4)"
description: FHIR® Implementation Guide for the Electronic Laboratory Report of the Swiss Federal Office of Public Health
status: active # draft | active | retired | unknown
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CHE
date: 2024-06-16
version: 1.4.0-cibuild
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: ci-build # release # ci-build 
publisher:
  name: Federal Office of Public Health FOPH
contact:
  - name: Federal Office of Public Health FOPH
    telecom:
      - system: url
        value: https://www.bag.admin.ch/bag/en/home/das-bag/kontakt-standort.html

dependencies:
  hl7.terminology: 5.4.0
  hl7.fhir.eu.laboratory: 0.1.0
  hl7.fhir.uv.ips: 1.1.0
  ch.fhir.ig.ch-lab-report: 1.0.0-ballot
  ch.fhir.ig.ch-core: 5.0.0-ballot
  hl7.fhir.uv.extensions.r4: 1.0.0
  hl7.fhir.extensions.r5: 4.0.1
pages:
  index.md:
    title: Home
  document.md:
    title: FHIR Document (Bundle)   
  logical.md:
    title: Logical Model  
  usecase-german.md:
    title: Anwendungsfälle 
  guidance.md:
    title: Guidance
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  api.md:
    title: API
  terminology.md:
    title: Terminology
  changelog.md:
    title: Changelog
  businessrules.md:
    title: Business Rules      

menu:
  Table of Contents: toc.html
  Home: index.html
  Laboratory Report: 
    FHIR Document: document.html
    Logical Model: logical.html
  Use Case:
    German: usecase-german.html
  Guidance: guidance.html
  Profiles: profiles.html
  Extensions: extensions.html
  API: api.html
  Terminology: terminology.html
  Changelog: changelog.html
  Business Rules: businessrules.html
  Artifacts: artifacts.html

# Parameters
# Core FHIR: http://build.fhir.org/codesystem-guide-parameter-code.html
# FHIR Tools IG: http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
parameters:
  allow-extensible-warnings: true
  display-warnings: true
  path-resource:
    - input/resources
    - fsh-generated/resources
  no-narrative: 
    - Bundle/*
    - Composition/*
    - DiagnosticReport/*
    - DocumentReference/*
    - Observation/*
    - Organization/*
    - Patient/*
    - Practitioner/*
    - PractitionerRole/*
    - ServiceRequest/*
    - Specimen/*

  excludettl: true
#  apply-version: false
#  default-version: true

instanceOptions:
  # Determines for which types of Instances SUSHI will automatically set meta.profile
  # if InstanceOf references a profile. Options are:
  # - always: Set meta.profile for all Instances of profiles (default)
  # - never: Do not set meta.profile on any Instances
  # - inline-only: Set meta.profile for only Instances of profiles with Usage set to #inline
  # - standalone-only: Set meta.profile for only Instances of profiles where Usage is any value other than #inline
  setMetaProfile: never

resources:
  Bundle/8Doc-HepatiteB:
    name: 8Doc - HepatiteB
    description: Document for Hepatite B
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/9Doc-HepatiteC:
    name: 9Doc - HepatiteC
    description: Example Document for Hepatite C
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/10Doc-Legionella:
    name: 10Doc - Legionella
    description: Example Document for Legionella
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/11Doc-Malaria:
    name: 11Doc - Malaria
    description: Example Document for Malaria
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/12Doc-Monkeypox:
    name: 12Doc - Monkeypox
    description: Example Document for Monkeypox
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Bundle/13Doc-Shigella:
    name: 13Doc - Shigella
    description: Example Document for Shigella
    exampleCanonical: http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict
  Binary/Test92-Bundle-WarningBerUidGln:
    extension:
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-format
        valueCode: application/fhir+json
    name: Test92 - Bundle provoking warning for Ber Uid and Gln
    description: Test bundle to verify if incorrect BerUid Gln are detected with warnings
    exampleCanonical: http://hl7.org/fhir/StructureDefinition/Binary
  TestScript/Test92-WarningBerUidGln:
    name: Test92 - Warning for Ber Uid and Gln
    description: Test script to verify if incorrect BerUid Gln are detected with warnings
  Binary/Test93-DocumentReference-Error-FullName-Influenca:
    extension:
      - url: http://hl7.org/fhir/tools/StructureDefinition/implementationguide-resource-format
        valueCode: application/fhir+xml
    name: Test93 - DocumentReference with contained Bundle provoking error for full name for Influenca (must be initials)
    description: Test DocumentReference with contained Bundle provoking error for full name for Influenca (must be initials)
    exampleCanonical: http://hl7.org/fhir/StructureDefinition/Binary
  TestScript/Test93-Error-FullName-Influenca:
    name: Test93 - Error if full name is provided by Influenca (should be initials)
    description: Test script to verify error if full name is provided by Influenca (must be initials)
  TestScript/Test94-Ignore-Source-Warning:
    name: Test94 - If warning is ignored for Binding for path (.+) has no source
    description: Test script to verify if warning is ignored for Binding for path (.+) has no source