# Example/Documentation for the IG YML file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

# Package name
# https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Packagename
id: ch.fhir.ig.ch-elm
canonical: http://fhir.ch/ig/ch-elm
name: CH_ELM
title: "CH ELM (R4)"
description: FHIR® Implementation Guide for the Electronic Laboratory Report of the Swiss Federal Office of Public Health
status: active # draft | active | retired | unknown
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CHE
date: 2023-11-16
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: trial-use # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: Federal Office of Public Health FOPH
contact:
  - name: Federal Office of Public Health FOPH
    telecom:
      - system: url
        value: https://www.bag.admin.ch/bag/en/home/das-bag/kontakt-standort.html

dependencies:
  ch.fhir.ig.ch-lab-report: current
  ch.fhir.ig.ch-core: current
  hl7.fhir.uv.extensions.r4: 1.0.0
  hl7.fhir.extensions.r5: 4.0.1

pages:
  index.md:
    title: Home
  document.md:
    title: FHIR Document (Bundle)   
  usecase-german.md:
    title: Anwendungsfälle 
  guidance.md:
    title: Infectious Diseases Requiring Notification
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  api.md:
    title: API
  terminology.md:
    title: Terminology
  changelog.md:
    title: Changelog       

menu:
  Home: index.html
  Laboratory Report: 
    FHIR Document: document.html
    Logical Model: StructureDefinition-LaboratoryReport.html
  Use Case:
    German: usecase-german.html
  Guidance: guidance.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  API: api.html
  Business Rules: CodeSystem-ch-elm-foph-business-rules.html
  Artifacts: artifacts.html

# Parameters
# Core FHIR: http://build.fhir.org/codesystem-guide-parameter-code.html
# FHIR Tools IG: http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
parameters:
  allow-extensible-warnings: true
  display-warnings: true
  path-resource:
    - input/resources
    - fsh-generated/resources
  no-narrative: 
    - Bundle/*
    - DocumentReference/*
  excludettl: true
#  apply-version: false
#  default-version: true
